# Guided Capstone Step 6. Documentation

**The Data Science Method**  


1.   Problem Identification 

2.   Data Wrangling 
  
3.   Exploratory Data Analysis 
 
4.   Pre-processing and Training Data Development

5.  Modeling

6.   **Documentation**
  * Review the Results
  * Finalize Code 
  * Finalize Documentation
  * Create a Project Report 
  * Create a Slide Deck for the Executive Audience

In this guided capstone we are going to revisit many of the actions we took in the previous guided capstone steps. This gives you the opportunity to practice the code you wrote to solve the questions in step 4 and 5. 

**<font color='teal'> Start by loading the necessary packages and printing out our current working directory just to confirm we are in the correct project directory. </font>**

In [247]:
import pandas as pd
from sklearn import linear_model
from sklearn.metrics import explained_variance_score,mean_absolute_error
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import os
import pandas as pd 
import datetime
import seaborn as sns 
import matplotlib.pyplot as plt
import numpy as np

os.getcwd()

'/Users/ray/Desktop/Projects/SPRINGBOARD/projects/Guided_Capstone_2'

## Fit Models with Training Dataset

**<font color='teal'> Using sklearn fit the model you chose in Guided Capstone 5 on your training dataset. This includes: creating dummy features for states if you need them, scaling the data,and creating train and test splits before fitting the chosen model.Also, remember to generate a model performance score(MAE, or explained variance) based on the testing hold-out data set.</font>**

In [248]:
    
def lin_reg(df, y):

    dfo=df.select_dtypes(include=['object']) # select object type columns
    x = pd.concat([df.drop(dfo, axis=1), pd.get_dummies(dfo)], axis=1)
    
    scaler2 = StandardScaler().fit(x)
    
    # Declare a variable called X_scaled, and assign it the result of calling the transform() method with parameter X 
    X_scaled =scaler2.transform(x)
        # Get the 1-dimensional flattened array of our response variable y by calling the ravel() function on y
    y = x[y].ravel()

    # Call the train_test_split() function with the first two parameters set to X_scaled and y 
    # Declare four variables, X_train, X_test, y_train and y_test separated by commas 
    X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.25, random_state=1)

    lm = linear_model.LinearRegression()
    model = lm.fit(X_train,y_train)
    y_pred = model.predict(X_test)
    
    data={'var':explained_variance_score(y_test, y_pred),  'mae':mean_absolute_error(y_test, y_pred)}
    return model, data, y_pred

#### Best Model 

In [249]:
df = pd.read_csv('./data/step2_output.csv').drop('Unnamed: 0', axis=1)

df = df.drop(['state','summit_elev','base_elev'], axis=1) 

model, data ,y_pred= lin_reg(df,'AdultWeekend')
print('variance: ' ,data['var'])
print('MAE: ', data['mae'])
print(y_pred.max())

variance:  0.835555140176336
MAE:  7.81928802766858
137.84106657050995


In [250]:
dfo=df.select_dtypes(include=['object']) # select object type columns
x = pd.concat([df.drop(dfo, axis=1), pd.get_dummies(dfo)], axis=1)

scaler2 = StandardScaler().fit(x)

# Declare a variable called X_scaled, and assign it the result of calling the transform() method with parameter X 
X_scaled =scaler2.transform(x)
    # Get the 1-dimensional flattened array of our response variable y by calling the ravel() function on y
y = x['AdultWeekend'].ravel()

# Call the train_test_split() function with the first two parameters set to X_scaled and y 
# Declare four variables, X_train, X_test, y_train and y_test separated by commas 
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.25, random_state=1)

lm = linear_model.LinearRegression()
model = lm.fit(X_train,y_train)
y_pred = model.predict(X_test)

data={'var':explained_variance_score(y_test, y_pred),  'mae':mean_absolute_error(y_test, y_pred)}

X_test

array([[-0.22762157, -0.30893969, -0.05513178, ..., -0.11076976,
        -0.22573306, -0.15762208],
       [ 1.38053152, -0.30893969, -0.05513178, ..., -0.11076976,
        -0.22573306, -0.15762208],
       [ 0.72332309,  1.4796585 , -0.05513178, ..., -0.11076976,
        -0.22573306, -0.15762208],
       ...,
       [-1.03064151, -0.30893969, -0.05513178, ..., -0.11076976,
        -0.22573306, -0.15762208],
       [-0.59743339, -0.30893969, -0.05513178, ..., -0.11076976,
        -0.22573306, -0.15762208],
       [ 0.1950205 , -0.30893969, -0.05513178, ..., -0.11076976,
        -0.22573306, -0.15762208]])

## Review the results 

**<font color='teal'> Now, let's predict the Big Mountain Weekend price with our model in order to provide a recommendation to our managers on how to price the `AdultWeekend` lift ticket. First we need to find the row for Big Mountain resort in our data using string contains or string matching.</font>**

In [251]:
big_mountain = df[df['Name'].str.contains('Big Mountain')]
big_mountain

Name   Region  vertical_drop  trams  fastEight  fastSixes  \
151  Big Mountain Resort  Montana           2353      0        0.0          0   

     fastQuads  quad  triple  double  ...  LongestRun_mi  SkiableTerrain_ac  \
151          3     2       6       0  ...            3.3             3000.0   

     Snow Making_ac  daysOpenLastYear  yearsOpen  averageSnowfall  \
151           600.0             123.0       72.0            333.0   

     AdultWeekday  AdultWeekend  projectedDaysOpen  NightSkiing_ac  
151          81.0          81.0              123.0           600.0  

[1 rows x 24 columns]

**<font color='teal'> Prepare the Big Mountain resort data row as you did in the model fitting stage.</font>**

In [254]:
dfo=big_mountain.select_dtypes(include=['object']) # select object type columns
big_mountain = pd.concat([big_mountain.drop(dfo, axis=1), pd.get_dummies(dfo)], axis=1)
big_mountain

ValueError: No objects to concatenate

In [253]:
bm_scaled = StandardScaler().fit_transform(np.array(big_mountain).reshape(1,-1))
bm_scaled

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.]])

In [257]:
bm_array = np.array(big_mountain)
bm_array

array([[2.353e+03, 0.000e+00, 0.000e+00, 0.000e+00, 3.000e+00, 2.000e+00,
        6.000e+00, 0.000e+00, 3.000e+00, 1.400e+01, 1.050e+02, 4.000e+00,
        3.300e+00, 3.000e+03, 6.000e+02, 1.230e+02, 7.200e+01, 3.330e+02,
        8.100e+01, 8.100e+01, 1.230e+02, 6.000e+02, 1.000e+00, 1.000e+00]])

**<font color='teal'> Predict the Big Mountain resort `Adult Weekend` price and print it out.</font>** This is our expected price to present to management. Based on our model given the characteristics of the resort in comparison to other ski resorts and their unique characteristics.

In [258]:
model.predict(bm_array)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 389 is different from 24)

**<font color='teal'> Print the Big Mountain resort actual `Adult Weekend` price.</font>**

**<font color='teal'> As part of reviewing the results it is an important step to generate figures to visualize the data story. We can use the clusters we added to our data frame to create scatter plots for visualizing the Adult Weekend values compared to other characteristics. Run the example below to get you started and build two or three more figures to include in your data story telling.</font>**

In [ ]:
#plt.scatter(df['summit_elev'], df['vertical_drop'], c=df['clusters'], s=50, cmap='viridis', label ='clusters')
#plt.scatter(ac['summit_elev'], ac['vertical_drop'], c='black', s=100)
#plt.xlabel('summit_elev')
#plt.ylabel('vertical_drop')
#plt.title('summit_elev by vertical_drop by cluster')
#plt.savefig('figures/fig1.png',bbox_inches='tight')

## Finalize Code

 Making sure our code is well organized and easy to follow is an important step. This is the time where you need to review the notebooks and Python scripts you've created and clean them up so they are easy to follow and succinct in nature. Addtionally, we will also save our final model as a callable object using Pickle for future use in a data pipeline. Pickle is a module that serializes (and de-serializes) Python objects so that they can become executable objects like functions. It's used extensively in production environments where machine learning models are deployed on an industrial scale!**<font color='teal'> Run the example code below to save out your callable model. Notice that we save it in the models folder we created in our previous guided capstone step.</font>** 

In [ ]:
#import pickle
#s = pickle.dumps(model)
#from joblib import dump, load
#dump(model, 'models/regression_model_adultweekend.joblib') 

## Finalize Documentation

For model documentation, we want to save the model performance metrics as well as the features included in the final model. You could also save the model perfomance metrics and coefficients fo the other models you tried in case you want to refer to them later. **<font color='teal'> Create a dataframe containing the coefficients and the model performance metrics and save it out as a csv file, then upload it to your github repository.</font>** 